spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/wallet}
spring.datasource.username=${DB_USERNAME:wallet}
spring.datasource.password=${DB_PASSWORD:wallet}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
